version: "3"

services:
  db:
    image: "postgis/postgis:15-3.3"
    restart: "always"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  api:
    container_name: timezones_api
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    links:
      - db
    volumes:
      - "./:/app"
    command: bash -c "
      python3 timezones/database.py &&
      uvicorn src.timezones.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  db:
    driver: local
